import fs from "fs";

export const titles = [
  "Project 1",
  "Project 2",
  "Project 3",
  "Project 4",
  "Project 5",
  "Project 6",
  "Project 7",
  "Project 8",
  "Project 9",
  "Project 10",
  "Project 11",
  "Project 12",
  "Project 13",
  "Project 14",
  "Project 15",
  "Project 16",
  "Project 17",
  "Project 18",
  "Project 19",
  "Project 20",
  "Project 21",
  "Project 22",
  "Project 23",
  "Project 24",
  "Project 25",
  "Project 26",
  "Project 27",
  "Project 28",
  "Project 29",
  "Project 30",
  "Project 31",
  "Project 32",
  "Project 33",
  "Project 34",
  "Project 35",
  "Project 36",
  "Project 37",
  "Project 38",
  "Project 39",
  "Project 40",
  "Project 41",
  "Project 42",
  "Project 43",
  "Project 44",
  "Project 45",
  "Project 46",
  "Project 47",
  "Project 48",
  "Project 49",
  "Project 50",
  "Project 51",
  "Project 52",
  "Project 53",
  "Project 54",
  "Project 55",
  "Project 56",
  "Project 57",
  "Project 58",
  "Project 59",
  "Project 60",
  "Project 61",
  "Project 62",
  "Project 63",
  "Project 64",
  "Project 65",
  "Project 66",
  "Project 67",
  "Project 68",
  "Project 69",
  "Project 70",
  "Project 71",
  "Project 72",
  "Project 73",
  "Project 74",
  "Project 75",
  "Project 76",
  "Project 77",
  "Project 78",
  "Project 79",
  "Project 80",
  "Project 81",
  "Project 82",
  "Project 83",
  "Project 84",
  "Project 85",
  "Project 86",
  "Project 87",
  "Project 88",
  "Project 89",
  "Project 90",
  "Project 91",
  "Project 92",
  "Project 93",
  "Project 94",
  "Project 95",
  "Project 96",
  "Project 97",
  "Project 98",
  "Project 99",
  "Project 100",
];

export const technologies = [
  "Project.Technologies",
  "Python, HTML, CSS, Machine Learning, Deep Learning",
  "Java Spring Boot, Hibernate, MySQL",
  "Java, HTML, CSS, JavaScript",
  "Websockets, Redis, Channel layers",
  "Python, Scrapy framework, MongoDB",
  "Postman, Docker, Jenkins, Java, Spring Boot",
  "React JS, JWT Authentication, Local Storage",
  "Python, Django, API",
  "React, Node, Java",
  "React JS, Redux, HTML, CSS, Bootstrap, Material UI, Socket.io, Python Django",
  "React JS, Node JS, TNT database",
  "React JS, Mongo DB, MVC architecture",
  "Python, Java, Redis, caching, pagination, liquibase",
  "Python, AWS, JavaScript, Node JS, Docker",
  "Java, Spring Framework",
  "SQL, Cloud, Ecommerce, Haru, Spoke",
  "HTML, CSS, Node.js, SQL, MongoDB",
  "Java, Spring Boot, Angular, HTML, CSS, JavaScript, SQL",
  "Machine learning, Linear and Logistic Regression",
  "AWS, Node JS, Aurora DB, React, Python, TypeScript, JavaScript, CICD pipelines, ECS containers and topics",
  "Django, Elasticview",
  "Third Party APIs, Encryption and Decryption Algorithms",
  "Java, React/TypeScript",
  "Java, Python, SQL, MongoDB, Mongoose, Passport, React and Express",
  "API, Event-based system",
  "React, React Native",
  "Fitbit API, Isolation Forest Algorithm, Email Service",
  "Node JS, Puppeteer",
  "Java, PostgreSQL",
  "React JS, Node JS, Express JS, MongoDB",
  "Python Django, Flask, Spring Boot",
  "Node JS, JavaScript",
  "Machine Learning, Random Forest, Extra Trees Regressor, Light Gradient Boosting",
  "CA framework, Python APIs, React",
  "Node JS, TypeScript, MongoDB",
  "Java, Retrofit, MVC pattern",
  "Multicast graded CNN model, Hybrid recommender system",
  "Java, JavaScript, Android app development, Firebase, Node.js, MongoDB, Postman",
  "React JS, Node JS, HTML, CSS, JavaScript, EJS",
  "Javascript, SQL, Report Labs, React, Python Django, Java, Spring Boot, MySQL",
  "DuckDuckGo API, React Native, TypeScript",
  "HTML, CSS, JavaScript, Tableau, Power BI, SQL, C++",
  ,
  "Decentralized anomaly detection system, machine learning, attention mechanism",
  "Azure APIs and SAS fulfillment APIs",
  "Java, AWS DynamoDB",
  "HTML, CSS, JavaScript, React JS, Python Django, Express",
  "PHP, JavaScript, jQuery, HTML, CSS, Bootstrap, MySQL, Node JS, Express JS, MongoDB",
  "Python, Django, HTML, CSS, JavaScript",
  "KN algorithm, Flutter, Dart, Firebase",
  "React, Node.js, API development",
  "Machine Learning, Smart Analysis",
  "React, Django",
  "Angular, React, Next js, Python Django, Express JS",
  "MongoDB, Express JS, Node JS, Java",
  "Solidity",
  "NLTK library, Text BLOB and SVC",
  "React Jsonschema, Material React Table, Promises, Batch Functions",
  "TypeScript, Node.js",
  "React, Angular, Next.js, Python, Django, Flask, MongoDB, MySQL",
  "React, Python, SQL, Java, C",
  "HTML, Form groups, S3 bucket",
  "Python, Django, Django Rest Framework",
  "Lambda, AWS, API gateway, React",
  "Django, React, Alpha Vantage API",
  "JavaScript, HTML, CSS, Google Fonts, React Icon, Responsiveness",
  "Digital Marketing",
  "React, Next JS, Node JS, Express, SQLite, MongoDB, Prisma",
  "Micro service architecture, Spring MVC, Spring Cloud",
  "TypeScript, FCM token, Socket IO, Google Descriptive APIs, Natural Language Processing",
  "Python, AI, ML",
  "Node JS, Express JS, MySQL, AWS, GitLab, Sonar, Swagger APIs",
  "React JS, Akka microservices, Postgres, MongoDB, Sequel",
  "Amazon SQS, Kafka",
  "Postman, JUnit, threads, Jenkins, Docker",
  "Cron job",
  "JavaScript",
  "Django, Front-end and Back-end development",
  "ASP.NET, CSS, HTML, SQL Server",
  "Java, WS, AWS, Lambda Functions, Cloud Watch, MongoDB, Express, React, Node JS",
  "EF Core API, Angular, Azure",
  "Machine learning, Linear regression",
  "JavaScript, External Libraries",
  "Machine Learning, Cosine Similarity",
  "React, Node, Express, MongoDB, PostgreSQL, Django, Python",
  "MongoDB, Angular, JavaScript, CSS, HTML, Python",
  "C++, Java, AWS, Spring Framework, J Unit, Machine Learning, Linux, AOP",
  "Open AI, Machine Learning Models, Python Libraries for Audio Conversion and Prompt Engineering",
  "Java, AWS Lambda",
  "MongoDB, Node JS, JavaScript, JWT, React Native",
  "Pega, Python Node JS, Theme Cosmos",
  "React, Next.js, Python Django, Node.js, Express.js",
  "Machine Learning, Front-end and Backend Frameworks, AWS",
  "JavaScript, HTML, CSS, Bootstrap, Express JS, Node JS",
  "CSS, HTML, CSS, JavaScript, Python, MySQL",
  "React JS, Redux, React Hooks",
  "React JS, Node.js",
  "Mongoose, React JS, Node JS",
  "Open pose, MRCP CNN, Pandas, scikit learn, Python",
  "React.js, Redux, Schema UI, Config one UI, Live Swiggy API, Conflict one UI",
  "Front-end and Back-end frameworks",
];

export const frontendSkills = [
  "HTML, CSS, JavaScript",
  "React JS",
  "React, HTML, CSS",
  "React",
  "React Native",
  "React, Angular",
  "React JS, HTML, CSS, JavaScript",
  "No experience",
  "React, Java, Angular, Node, JavaScript",
  "React JS, HTML, CSS, Bootstrap, Material UI",
  "HTML, CSS, JavaScript, React JS",
  "React JS",
  "React, Next js",
  "Angular, JavaScript, TypeScript",
  "React",
  "React, Angular, Next.js",
  "HTML, CSS, React",
  "Angular, React, Next js",
  "React, Angular",
  "React",
  "React",
  "Angular, React, Next.js",
  "React, Next JS, Google Auth",
  "React JS (Beginner level, Self-rated 7/10)",
  "Reactjs",
  "React, React Native",
  "React",
  "JavaScript, React, Angular",
  "React",
  "HTML, CSS, JavaScript, jQuery",
  "ReactJS",
  "Angular, React, Next js",
  "React JS",
  "React",
  "Not Specified",
  "React Native",
  "Not mentioned",
  "React, HTML, CSS",
  "React JS, HTML, CSS, JavaScript, EJS",
  "React, HTML, CSS, JavaScript",
  "React Native",
  "HTML, CSS, JavaScript, React JS",
  "Angular, React, Next js",
  "",
  "Learning React.js",
  "HTML, CSS, JavaScript, React JS",
  "Bootstrap, JavaScript, jQuery",
  "Angular, React, Next js",
  "React",
  "React",
  "Not Specified",
  "React",
  "Angular, React, Next js",
  "Angular, React, Next js",
  "React.js",
  "Not Mentioned",
  "React, CJS, Redux, HTML, CSS",
  "Angular",
  "React, Angular, Next.js",
  "React",
  "Angular, React, Next.js",
  "No information provided",
  "React, Redux",
  "React",
  "React, TypeScript",
  "React, Angular",
  "React, Next JS",
  "Interest in learning",
  "Not specified",
  "React JS",
  "React",
  "Angular JS, React",
  "Angular, React, Next js",
  "Angular, React, Next js",
  "React",
  "JavaScript, React",
  "Basic knowledge",
  "CSS, HTML, JavaScript, Ajax, Bootstrap",
  "ReactJS",
  "Angular JS",
  "Undetermined",
  "Angular, React, Next js",
  "React, HTML, CSS, JavaScript",
  "React",
  "Angular, React, Next.js",
  "JavaScript, React JS, HTML, CSS",
  "4-5/10",
  "React",
  "Reactjs, React Native",
  "Python Node JS",
  "React, Next.js",
  "Unknown",
  "React, Redux, HTML, JavaScript, CSS, Bootstrap",
  "Angular, React, Next js",
  "HTML, CSS, JavaScript, React JS",
  "React JS",
  "React JS",
  "HTML, JavaScript, jQuery, CSS",
  "React.js",
  "7.5/10",
];

export const backendSkills = [
  "Python",
  "Java, Spring Boot, Hibernate",
  "Java, Python Django, Flask",
  "Python Django, Django Rest",
  "Python, Django",
  "Spring Boot, Java",
  "Node JS",
  "Python Django, API",
  "Node",
  "Python Django",
  "Node JS",
  "Mongo DB",
  "Python Django and Spring frameworks",
  "Python, Java, Node JS, AWS Lambda functions",
  "Python, Django, Java, Spring Framework",
  "SQL, MySQL, Oracle, Java, NoSQL",
  "Node.js",
  "Python Django, Spring",
  "Python Django, Java Spring",
  "Python, Node.js",
  "Django",
  "Node.js, Express",
  "Java Spring Framework",
  "Java, Python, SQL (Self-rated 7/10)",
  "Node JS, TypeScript, JavaScript",
  "Not experienced, but a quick learner",
  "Express, JavaScript",
  "Node JS, Express, Python, Django",
  "Java",
  "PHP Codeigniter, Django",
  "Python Django, Flask, Spring Boot",
  "Node.js, Python Django",
  "Node JS, Express JS",
  "Python, Node.js",
  "Node JS",
  "Java",
  "Back-end frameworks and APIs",
  "Node.js",
  "Node JS",
  "Python Django, Java, Spring Boot",
  "Prayat",
  "None mentioned",
  "Java, Spring Boot, JavaScript API",
  "Azure APIs and SAS fulfillment APIs",
  "Java",
  "Python Django, Express",
  "PHP, Node.js, Express.js",
  "Python Django, ASP.NET",
  "Node.js",
  "Node.js",
  "Django",
  "Django",
  "Python Django, Express JS",
  "Python Django, Node.js",
  "Node.js",
  "Python",
  "Python",
  "Node.js",
  "Python, Django, Flask",
  "Python Flask",
  "Spring Boot, Django",
  "Python, Django, Django Rest Framework",
  "Node.js, Python Django",
  "Python Django",
  "Node, Express",
  "Node",
  "Node JS, Express",
  "Java, Spring and Spring boot framework, REST APIs, micro services architecture",
  "Python",
  "Django, Python",
  "Node.js, Express.js",
  "Scala, Akka, Play framework",
  "Python Django",
  "Python Django, Spring Boot",
  "Not specified",
  "JavaScript",
  "Basic knowledge",
  "ASP.NET MVC",
  "NodeJS, ExpressJS",
  ".Net, SQL",
  "Python, FAST API",
  "Python",
  "",
  "Node, Express, Django, Python",
  "Python Django, Fast APIs, Notes",
  "Node JS, Java, AWS, Spring Framework",
  "Python Django, 7-8/10",
  "Node.js, Express.js",
  "Node.js, Express",
  "No prior experience with backend frameworks",
  "Python Django, Node.js, Express.js",
  "Unknown",
  "Express JS, Node JS",
  "No Experience",
  "Node JS, C&C",
  "Node.js (Learning)",
  "Node JS",
  "Python, Django",
  "Willing to learn",
  "08-Oct",
];

export const databaseSkills = [
  "",
  "MySQL",
  "MySQL, MongoDB, Postgres",
  "MySQL",
  "MongoDB",
  "",
  "MongoDB",
  "Not mentioned",
  "SQL",
  "",
  "SQL, TNT",
  "Mongo DB",
  "Not Specified",
  "SQL",
  "Not Mentioned",
  "SQL, MySQL, Oracle, NoSQL",
  "SQL, MongoDB",
  "SQL",
  "",
  "Aurora DB",
  "Not mentioned",
  "Not Mentioned",
  "Not Specified",
  "MongoDB, SQL",
  "Postgre SQL",
  "Not mentioned",
  "Not Mentioned",
  "",
  "PostgreSQL",
  "MongoDB",
  "",
  "Postman",
  "Not mentioned",
  "Not mentioned",
  "MongoDB",
  "Not mentioned",
  "Not mentioned",
  "MongoDB, Firebase",
  "Not Mentioned",
  "MySQL, Sequel Lite",
  "Not mentioned",
  "SQL",
  "Not mentioned",
  "SQL and NoSQL",
  "AWS DynamoDB",
  "Not mentioned",
  "MySQL, MongoDB",
  "",
  "",
  "MongoDB",
  "Not Specified",
  "Not mentioned",
  "Not mentioned",
  "MongoDB",
  "MongoDB",
  "Not Mentioned",
  "Unknown",
  "Not Mentioned",
  "MongoDB, MySQL",
  "SQL",
  "MySQL",
  "No information provided",
  "Not mentioned",
  "Not mentioned",
  "Not Mentioned",
  "Not Mentioned",
  "SQLite, MongoDB, Prisma",
  "Hadoop ecosystem",
  "Not specified",
  "Not specified",
  "MongoDB, MySQL",
  "Postgres, MongoDB",
  "Unspecified",
  "",
  "Not specified",
  "Not Discussed",
  "Not mentioned",
  "SQL Server",
  "MongoDB",
  "SQL",
  "Undetermined",
  "Not Mentioned",
  "",
  "MongoDB, PostgreSQL",
  "MongoDB",
  "Not mentioned",
  "Not Mentioned",
  "MongoDB",
  "MongoDB, PostgreSQL",
  "Not mentioned",
  "Unknown",
  "Unknown",
  "MongoDB",
  "MySQL",
  "Not provided",
  "Not Mentioned",
  "Mongoose",
  "MySQL, MSSQL",
  "Good understanding of data structures and algorithms",
  "Not Mentioned",
];

export const infrastructureSkills = [
  "",
  "Not specified",
  "AWS, Azure OCR, Apache, Docker",
  "Not Mentioned",
  "Not Specified",
  "Postman, Docker, Jenkins",
  "Not Mentioned",
  "Not mentioned",
  "",
  "",
  "Not mentioned",
  "Not mentioned",
  "Not Specified",
  "Docker, AWS",
  "Not Mentioned",
  "Cloud platforms",
  "Not Mentioned",
  "HTTPD",
  "",
  "AWS, ECS containers",
  "Not mentioned",
  "Not Mentioned",
  "Not Specified",
  "No information provided",
  "Flutter",
  "Not mentioned",
  "Not Mentioned",
  "AWS",
  "Not Mentioned",
  "Not specified",
  "",
  "",
  "Not mentioned",
  "Not mentioned",
  "Not Specified",
  "Not mentioned",
  "Not mentioned",
  "Firebase",
  "Not Mentioned",
  "",
  "Not mentioned",
  "None mentioned",
  "Not mentioned",
  "",
  "AWS",
  "Not mentioned",
  "Not Mentioned",
  "",
  "",
  "Not mentioned",
  "Not Specified",
  "Not mentioned",
  "Not mentioned",
  "Not mentioned",
  "Not provided",
  "Not Mentioned",
  "Messenger, Python, and machine learning",
  "Not Mentioned",
  "Not Provided",
  "",
  "Engine X",
  "No information provided",
  "AWS",
  "Not mentioned",
  "Not Mentioned",
  "Not Mentioned",
  "Not Mentioned",
  "Micro services architecture",
  "Not specified",
  "Not specified",
  "AWS",
  "Not specified",
  "Docker",
  "Docker, Jenkins",
  "Not specified",
  "Not Discussed",
  "Not mentioned",
  "Not Mentioned",
  "AWS",
  "Azure",
  "PyCharm",
  "Not Mentioned",
  "",
  "",
  "Not Mentioned",
  "AWS",
  "Not Mentioned",
  "AWS",
  "Knowledge not specified",
  "Not mentioned",
  "Unknown",
  "AWS",
  "Not provided",
  "No Experience",
  "Not provided",
  "Not Mentioned",
  "Not Mentioned",
  "Not Mentioned",
  "Not Mentioned",
  "Azure DevOps",
];

const createProjectList = () => {
  const projectList = [];
  for (let i = 0; i < 100; i++) {
    const project = {
      title: titles[i],
      technologies: technologies[i],
      skills: {
        frontend: frontendSkills[i],
        backend: backendSkills[i],
        database: databaseSkills[i],
        infrastructure: infrastructureSkills[i],
      },
    };

    projectList.push(project);

    console.log(JSON.stringify(projectList));

    fs.writeFileSync("data.json", JSON.stringify(projectList));
  }
};

createProjectList();
